---
title: "Metacycle analysis of Xenium circadian disruption experiment (Salk2025)"
format: html
server: shiny
Authors: HC, TC, YS
---



```{r}
if(!require(tidyr)){install.packages("dplyr")}
if(!require(MetaCycle)){install.packages("MetaCycle")}
if(!require(arrow)){install.packages("arrow")}
```


```{r}


setwd = '/media/volume/volume_spatial/hugo/R/'

source("ref_function.R")

date = Sys.Date()
run_name = "SD1"
condition = c("celltype","region")
circascore = "all"
sudoreplicates = 3

siglist = list()
clocklist = list()

path_to_data = paste0('./data/',run_name,'_norm_combined.parquet')
if (length(condition) == 2) {
  path_to_save = paste0("./Results/",date,"_",run_name,"_",condition[1],condition[2])
} else {
    path_to_save = paste0("./Results/",date,"_",run_name,"_",condition)
    }


dir.create(path_to_save)
dir.create(paste0(path_to_save,"/Raw"))
dir.create(paste0(path_to_save,"/Summary"))

```

Data import and pre-processing
```{r}

data = PreProcessingData(run_name, path_to_data, circascore)

if ("celltype" %in% condition){
  celltypes = GetValidCells(run_name)
}

if ("region" %in% condition){
  regions = GetValidRegions(run_name)
}

```

Run MetaCycle for all conditions

```{r}
if ("celltype" %in% condition & "region" %in% condition){
  print("WIP")
} else if ("celltype" %in% condition){
  MetaCycleCelltype(data, condition)
} else if ("region" %in% condition){
MetaCycleRegion(data, condition)
} else {print("condition not recognized")}
```



```{r}


```