---
title: "Metacycle analysis of Xenium circadian disruption experiment (Salk2025)"
format: html
server: shiny
Authors: HC, TC, YS
---



```{r}
library(dplyr)
library(arrow)
library(readr)
library(MetaCycle)
library(knitr)
library(logr)
```


```{r}
source("ref_function.R")

date = Sys.Date()
run_name = "SD1"
#condition can be celltype, class, neurotransmitter, and region)
condition = c("celltype")
condition_string <- paste(condition, collapse = "_and_")
circascore = "all"

siglist <- list()
siglistBH = list()
clocklist = list()

path_to_save = paste0("../R/Results/",date,"_",run_name,"_",condition_string)

dir.create(path_to_save, recursive = TRUE)
dir.create(paste0(path_to_save,"/Raw"))
dir.create(paste0(path_to_save,"/Summary"))

```

Data import and pre-processing
```{r}
setwd('/media/volume/volume_spatial/hugo/R/')

tmp = file.path(paste0('log/',date,'_metacycle_log.log'))
lf = log_open(tmp)

data = PreProcessingData(run_name, circascore)

use_gene_lists <- TRUE
gene_list_directory <- paste0("/media/volume/volume_spatial/hugo/R/data/gene_list_",run_name)

```

Run MetaCycle for all conditions

```{r}
MetaCycleAnalysis(
  data = data, 
  condition = condition, 
  run_name = run_name, 
  path_to_save = path_to_save, 
  date = date,
  use_gene_lists = use_gene_lists,
  gene_list_path = gene_list_directory
)

#log_close()
```

